### ISSUE TITLE
Tanımlanmamış Jargon Linklerinde Sonsuz Döngü Oluşuyor

### ISSUE THREAD

**Issue by aligoren** [alpcanaydin/jargon.ist#25]
Merhaba. Tanımlanmamış jargon linklerini açmaya çalışırken bir problem yaşadım. Sorunun kullandığım Firefox tabanlı bir sorun olup olmadığını bilmediğim için iki farklı tarayıcıda da deneme gerçekleştirdim.

## Kullanılan Tarayıcı Bilgisi

Firefox Quantum 59.0.2

## Başarılı Olan Tarayıcı Bilgisi

Chromium: 65.0.3325.181
Opera: 51.0.2830.55

## Kullanılan Eklentiler

Chromium: uBlock Origin
Firefox: Eklenti kurulu değil

## Problem

Henüz oluşturulmamış jargonlara gitmeye çalıştığımda sonsuz döngü ortaya çıkıyor.

## Problemin Ortaya Çıkışı ve Davranışı

1-) Buradaki linkte [https://jargon.ist/xhr](https://jargon.ist/xhr) **fetch** bağlantısına tıklayınca sonsuz bir döngü yaşanıyor. Bu işlemi beklediğimde bir şekilde 404.html sayfasına yönleniyor.

2-) [https://jargon.ist/fetch](https://jargon.ist/fetch) linkine adres satırından direkt gidersek bazen **Sayfa Bulunamadı** uyarısı verirken bazen sonsuz döngü oluşuyor. Bu işlemi beklediğimde bir şekilde 404.html sayfasına yönleniyor.

3-) Yukarıda belirttiğim başarılı tarayıcılarda bile hafif bir titreme var. network tooldan kontrol ettiğimde başarılı olan tarayıcılarda bile çiftleme yaşandığını fark ettim.

Teşekkürler.

**Comment by alpcanaydin** [comment]
Merhaba, evet ben de karsilastim simdi, tesekkurler bildirim için inceleyecegim en kisa zamanda.

**Comment by alpcanaydin** [comment]
Maalesef bu problem kullandigimiz Gatsby ile alakaliymis, onlar bir cozum buldugu zaman burada da duzeltiriz, tekrar tesekkurler bildirim icin.
